name: Tests

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform:
          - ubuntu-latest  
        python-version: [3.4, 3.5, 3.6, 3.7, 3.8, 3.9, pypy3]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: | 
        pip install -e .
    - name: Test with tox
      run: tox